/*******************************************************************************
* File:       SubGUIClass.h
* Name:       Josiah Lansford
* Date:       8 November 2019
* Assignment: HW5
* Purpose:    SubGUIClass inheriting from auto-generated wxWidgets GUIClass.
*             Contains handler functions and game logic for Tic Tac Toe.
*******************************************************************************/

#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"

//// end generated include
#include <string>

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
  private:
    // Keep array of pointers to buttons
    wxButton* buttonArray[9];

    // Keep array of game state (red vs orange)
    int gameBoard[9];

    // Remember if it is Orange or Blue's turn
    bool isBlueTurn;

    // Remember if game is over so we don't have to check again
    bool gameOver;

    void updateStatusBar();
    bool isGameOver();
    void resetGame();
    void endGame();
        
	protected:
		// Handlers for GUIClass events.
		void onButtonClick( wxCommandEvent& event );
		void onResetEvent( wxCommandEvent& event );
		void onExitEvent( wxCommandEvent& event );
    void OnClose(wxCloseEvent& event );

	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
	//// end generated class members
	
};

#endif // __SubGUIClass__
