#ifndef __SubGUIClass__
#define __SubGUIClass__

/**
@file
Subclass of GUIClass, which is generated by wxFormBuilder.
*/

#include "GUIClass.h"

//// end generated include
#include <string>

/** Implementing GUIClass */
class SubGUIClass : public GUIClass
{
  private:
    // Keep array of pointers to buttons
    wxButton* buttonArray[9];

    // Keep array of game state (red vs orange)
    int gameBoard[9];

    // Remember if it is Orange or Blue's turn
    bool isBlueTurn;

    void updateGame();
    bool isGameOver();
    void resetGame();
    void endGame();
    void confirmExit();
        
	protected:
		// Handlers for GUIClass events.
		void onButtonClick( wxCommandEvent& event );
		void onResetEvent( wxCommandEvent& event );
		void onExitEvent( wxCommandEvent& event );
		void onResetClick( wxCommandEvent& event );


	public:
		/** Constructor */
		SubGUIClass( wxWindow* parent );
	//// end generated class members
	
};

#endif // __SubGUIClass__
